# Default values for backend-groupe1-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: esgi-tp-group1

replicaCount: 3

image:
  repository: kuramoto/spring-boot-rest
  pullPolicy: IfNotPresent
  tag: "7"


service:
  name: backend-groupe1-chart-svc
  type: ClusterIP
  api:
    port: 80
  apimonitor:
    port: 81

volume:
  pv:
    name: backend-groupe1-chart-pv
    path: /data/backend-group1
    accessMode: ReadWriteOnce
    reclaimPolicy: Delete
    storage: 1Gi
  pvc:
    name: backend-groupe1-chart-pvc
    accessMode: ReadWriteOnce
    storage: 1Gi

secret:
  name: backend-groupe1-chart-secret
  type: Opaque
  data:
    username: YWRtaW4K
    password: YWRtaW4K