---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    purpose: backend
    group: group1
    organization: esgi
type: {{ .Values.secret.type }}
data:
  username: {{ .Values.secret.data.username }}
  password: {{ .Values.secret.data.password }}
