---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    purpose: database
    group: group1
    organization: esgi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: app-database
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: rootpassword
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: userpassword
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: database
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
          
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvc.name }}
