---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.pv.name }}
  labels:
    purpose: database
    group: group1
    organization: esgi
spec:
  capacity:
    storage: {{ .Values.volume.pv.storage }}
  accessModes:
    - {{ .Values.volume.pv.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.volume.pv.reclaimPolicy }}
  hostPath:
    path: {{ .Values.volume.pv.path }}
  storageClassName: {{ .Values.volume.storageclass }}
