---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    purpose: database
    group: group1
    organization: esgi
type: {{ .Values.secret.type }}
data:
  username: {{ .Values.secret.data.username }}
  userpassword: {{ .Values.secret.data.userpassword }}
  rootpassword: {{ .Values.secret.data.rootpassword }}