apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    purpose: frontend
    group: group1
    organization: esgi
data:
  username: {{ .Values.secret.data.username }}
  password: {{ .Values.secret.data.password }}
