---
apiVersion: v1
kind: Secret
metadata:
  name: backend-group1-secret
  namespace: esgi-tp-group1
  labels:
    purpose: backend
    group: group1
    organization: esgi
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

