---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-group1-pv
  labels:
    purpose: backend
    group: group1
    organization: esgi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/backend-group1
