---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-group1-pvc
  namespace: esgi-tp-group1
  labels:
    purpose: backend
    group: group1
    organization: esgi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
