---
apiVersion: v1
kind: Service
metadata:
  name: backend-group1-svc
  namespace: esgi-tp-group1
  labels:
    purpose: backend
    group: group1
    organization: esgi
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: api
      port: 80
      targetPort: 8090
    - protocol: TCP
      name: op
      port: 81
      targetPort: 8091
